### ISSUE TITLE
能否适配一下hexo的Stellar主题呢

### ISSUE THREAD

**Issue by kuhehe** [rqh656418510/hexo-readmore#4]
不知道大佬能否适配一下hexo的Stellar主题呢
主题仓库 
https://github.com/xaoxuu/hexo-theme-stellar
官方文档 
https://xaoxuu.com/wiki/stellar
谢谢大佬！！期待中。。！！！！

**Comment by rqh656418510** [comment]
亲测 Hexo 引流插件是兼容 Stellar 主题的，根据 [官方文档](https://docs.techgrow.cn/v1/wechat/tutorial/hexo/) 安装和配置插件即可。
